#============================

# FROM ubuntu:latest
# CMD ["echo", "hello"]


# echo is the shell command
# hello is the argument to that command

# docker build -t printer:v1 .

#============================

# FROM ubuntu:latest
# ENTRYPOINT ["echo"]

# run echo
# but no argument
# user has to pass the argument 

# docker run printer:v2 hello

#============================

FROM ubuntu:latest
ENTRYPOINT ["echo"]
cmd ["hello"]

